apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtrader-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudtrader-api
  template:
    metadata:
      labels:
        app: cloudtrader-api
    spec:
      containers:
      - name:cloudtrader-api
        image: cloudtrader.azurecr.io/cloudtrader-api:v1
        ports:
        - containerPort: 80